# Each new term in the Fibonacci sequence is generated by adding the previous two terms. 
# By starting with 1 and 2, the first 10 terms will be:

# 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

# By considering the terms in the Fibonacci sequence whose values do not exceed four 
# million, find the sum of the even-valued terms.


maxValue = 4000000
sum = 0
first = 1
second = 1

while second < int(maxValue):
    if second % 2 == 0:
        sum += second
    currentValue = first + second
    first = second
    second = currentValue

print("The sum of all even numbers in Fibonacci sequence up to the max sequence value of {max} is: {sum}".format(max=maxValue, sum=sum))
